using System;
using System.Collections.Generic;
namespace LostArkLogger
{
    public class PKTInitPC
    {
        public PKTInitPC(BitReader reader)
        {
            field0 = reader.ReadByte();
            field1 = reader.ReadUInt32();
            field2 = reader.ReadByte();
            field3 = reader.ReadByte();
            field4 = reader.ReadByte();
            field5 = reader.ReadUInt16();
            field6 = reader.ReadByte();
            field7 = reader.ReadUInt32();
            field8 = reader.ReadUInt64();
            field9 = reader.ReadByte();
            field10 = reader.ReadByte();
            field11 = reader.ReadUInt32();
            field12 = reader.ReadUInt16();
            field13 = reader.ReadUInt32();
            field14 = reader.ReadUInt32();
            field15 = reader.ReadUInt32();
            field16 = reader.ReadUInt32();
            field17 = reader.ReadByte();
            field18 = reader.ReadUInt64();
            field19 = reader.ReadUInt32();
            field20 = new Struct43(reader);
            field21 = reader.ReadByte();
            field22 = reader.ReadByte();
            field23 = reader.ReadByte();
            field24 = new Struct44(reader);
            field25 = reader.ReadByte();
            field26 = reader.ReadUInt16();
            statPair = new StatPair(reader);
            field28 = reader.ReadBytes(112);
            Name = reader.ReadString();
            field30 = reader.ReadUInt16();
            field31 = reader.ReadUInt32();
            field32 = new Struct45(reader);
            field33 = reader.ReadByte();
            PlayerId = reader.ReadUInt64();
            field35 = reader.ReadByte();
            field36 = new Struct46(reader);
            field37 = new Struct47(reader);
            field38 = reader.ReadByte();
            field39 = reader.ReadByte();
            field40 = reader.ReadUInt64();
            field41 = reader.ReadBytes(25);
            hasfield42 = reader.ReadByte();
            if (hasfield42 == 1)
                field42 = reader.ReadUInt32();
            field43 = reader.ReadUInt16();
            field44 = reader.ReadByte();
            field45 = new Struct12(reader);
            field46 = reader.ReadUInt16();
            field47 = reader.ReadByte();
            field48 = new Struct15(reader);
            field49 = reader.ReadByte();
            field50 = reader.ReadByte();
            field51 = reader.ReadByte();
            field52 = reader.ReadUInt32();
        }
        public Byte field0;
        public UInt32 field1;
        public Byte field2;
        public Byte field3;
        public Byte field4;
        public UInt16 field5;
        public Byte field6;
        public UInt32 field7;
        public UInt64 field8;
        public Byte field9;
        public Byte field10;
        public UInt32 field11;
        public UInt16 field12;
        public UInt32 field13;
        public UInt32 field14;
        public UInt32 field15;
        public UInt32 field16;
        public Byte field17;
        public UInt64 field18;
        public UInt32 field19;
        public Struct43 field20;
        public Byte field21;
        public Byte field22;
        public Byte field23;
        public Struct44 field24;
        public Byte field25;
        public UInt16 field26;
        public StatPair statPair;
        public Byte[] field28;
        public String Name;
        public UInt16 field30;
        public UInt32 field31;
        public Struct45 field32;
        public Byte field33;
        public UInt64 PlayerId;
        public Byte field35;
        public Struct46 field36;
        public Struct47 field37;
        public Byte field38;
        public Byte field39;
        public UInt64 field40;
        public Byte[] field41;
        public Byte hasfield42;
        public UInt32 field42;
        public UInt16 field43;
        public Byte field44;
        public Struct12 field45;
        public UInt16 field46;
        public Byte field47;
        public Struct15 field48;
        public Byte field49;
        public Byte field50;
        public Byte field51;
        public UInt32 field52;
    }
}
