/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class PKTPartyStatusEffectRemoveNotify
    {
        public PKTPartyStatusEffectRemoveNotify(BitReader reader)
        { 
            StatusEffectIds = reader.ReadList<Struct_107>();
            Unk1 = reader.ReadByte();
            PartyId = reader.ReadUInt64();
        }

        public List<Struct_107> StatusEffectIds { get; }
        public byte Unk1 { get; }
        public UInt64 PartyId { get; }
    }
}