/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class PKTPartyStatusEffectAddNotify
    {
        public PKTPartyStatusEffectAddNotify(BitReader reader)
        {
            Unk0 = new Struct_394(reader);
            Unk1 = reader.ReadByte();
            // the
            PartyId = reader.ReadUInt64();
            PlayerIdOnRefresh = reader.ReadUInt64();
        }

        public Struct_394 Unk0 { get; } = new Struct_394();
        public byte Unk1 { get; }
        //the effect target
        public UInt64 PartyId { get; }
        // this is not always set, seems to be set when "refreshing" an effect
        public UInt64 PlayerIdOnRefresh { get; }
    }
}