/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class PKTStatusEffectRemoveNotify
    {
        public PKTStatusEffectRemoveNotify(BitReader reader)
        {
            PlayerId = reader.ReadUInt64();
            StatusEffectIds = reader.ReadList<Struct_107>();
            Unk2 = reader.ReadByte();
        }

        public UInt64 PlayerId { get; }
        public List<Struct_107> StatusEffectIds { get; }
        public byte Unk2 { get; }
    }
}