/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class Struct_393
    {
        public bool valid = false;
        internal Struct_393()
        {
            //Made for conditional structures
        }

        internal Struct_393(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadUInt16();
            if(Unk0 <= 80)
            {
                Unk0_0 = reader.ReadBytes(12*Unk0);
            }
        }

        public UInt16 Unk0 { get; }
        public byte[] Unk0_0 { get; }
    }
}