/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class Struct_107
    {
        public bool valid = false;
        internal Struct_107()
        {
            //Made for conditional structures
        }

        public Struct_107(BitReader reader)
        {
            valid = true;
            InstanceId = reader.ReadUInt32();
        }

        public UInt32 InstanceId { get; }
    }
}