/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;

namespace LostArkLogger
{
    public class Struct_394
    {
        public bool valid = false;
        internal Struct_394()
        {
            //Made for conditional structures
        }

        internal Struct_394(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadUInt16();
            if(Unk0 <= 80)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    Unk0_0_0.Add(new Struct_662(reader));
                }
            }
        }

        public UInt16 Unk0 { get; }
        public List<Struct_662> Unk0_0_0 { get; } = new List<Struct_662>();
    }
}